DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS workouts;
DROP TABLE IF EXISTS exercises;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE workouts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	user_id INTEGER NOT NULL,
	date TEXT NOT NULL,
	workout_name TEXT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user (id)
);

CREATE TABLE exercise (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	workout_id INTEGER NOT NULL,
	exercise_name TEXT NOT NULL,
	sets INTEGER NOT NULL,
	reps INTEGER NOT NULL,
	weight REAL NOT NULL,
	FOREIGN KEY (workout_id) REFERENCES workout (id)
);
